### ISSUE TITLE
Getting Error Angular is not  defined

### ISSUE THREAD

**Issue by asadbsse** [ionic-team/ionic-todo#1]
Getting the following error while running the ionic-todo example.I have downloaded all files from gethub.

Uncaught ReferenceError: angular is not defined ionic-angular.js:19
Uncaught ReferenceError: angular is not defined app.js:1

**Comment by Ionitron** [comment]
Greetings @asadbsse!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
